# -*- coding: utf-8 -*-
"""addition.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_85SHMOC1cQbepXcB7saHSMMW49zGcJF
"""

# Question 1: Add 15 and 20
a = 15
b = 20
print("Answer 1 =", a + b)

# Question 2: Add 45 and 35
a = 45
b = 35
print("Answer 2 =", a + b)

# Question 3: Add 120 and 80
a = 120
b = 80
print("Answer 3 =", a + b)

# Question 4: Add 250 and 150
a = 250
b = 150
print("Answer 4 =", a + b)

# Question 5: Add 999 and 1
a = 999
b = 1
print("Answer 5 =", a + b)

# Question 6: Add 75 and 125
a = 75
b = 125
print("Answer 6 =", a + b)

# Question 7: Add 560 and 240
a = 560
b = 240
print("Answer 7 =", a + b)

# Question 8: Add 1000 and 500
a = 1000
b = 500
print("Answer 8 =", a + b)

# Question 9: Add 345 and 655
a = 345
b = 655
print("Answer 9 =", a + b)

# Question 10: Add 4321 and 1234
a = 4321
b = 1234
print("Answer 10 =", a + b)

